import * as cdk from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as rds from 'aws-cdk-lib/aws-rds';
import { Construct } from 'constructs';
import { resourceName } from '../config';
import { EnvironmentConfig } from '../environment-config';
import { NetworkStack } from './network-stack';

interface DatabaseStackProps extends cdk.StackProps {
  network: NetworkStack;
  config: EnvironmentConfig;
}

/**
 * DatabaseStack — RDS PostgreSQL 16 in private subnets.
 *
 * - db.t3.micro for POC (free-tier eligible)
 * - Single-AZ (Multi-AZ adds cost; enable for production)
 * - Credentials auto-generated by RDS and stored in Secrets Manager
 * - Automated backups retained for 7 days
 *
 * P4-05
 */
export class DatabaseStack extends cdk.Stack {
  public readonly instance: rds.DatabaseInstance;
  public readonly credentials: rds.DatabaseSecret;

  constructor(scope: Construct, id: string, props: DatabaseStackProps) {
    super(scope, id, props);

    const { config } = props;
    const { vpc, rdsSg } = props.network;

    // RDS auto-rotated credentials stored in Secrets Manager
    this.credentials = new rds.DatabaseSecret(this, 'DbCredentials', {
      secretName: 'tarpan/db-credentials',
      username: 'tarpan',
    });

    const subnetGroup = new rds.SubnetGroup(this, 'DbSubnetGroup', {
      description: 'Tarpan RDS subnet group - private subnets',
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      subnetGroupName: resourceName('db-subnet-group'),
    });

    this.instance = new rds.DatabaseInstance(this, 'DbInstance', {
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_16,
      }),
      instanceType: config.dbInstanceType,
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      subnetGroup,
      securityGroups: [rdsSg],
      credentials: rds.Credentials.fromSecret(this.credentials),
      databaseName: 'tarpan',
      instanceIdentifier: resourceName('postgres'),
      multiAz: config.dbMultiAz,
      storageEncrypted: true,
      allocatedStorage: 20,
      maxAllocatedStorage: 100,
      backupRetention: cdk.Duration.days(config.dbBackupRetentionDays),
      deletionProtection: config.dbDeletionProtection,
      removalPolicy: config.dbRemovalPolicy,
      enablePerformanceInsights: config.dbEnablePerformanceInsights,
      cloudwatchLogsExports: ['postgresql'],
    });

    // ── Outputs ───────────────────────────────────────────────────────────

    new cdk.CfnOutput(this, 'DbEndpoint', {
      value: this.instance.instanceEndpoint.hostname,
      exportName: `${this.stackName}-DbEndpoint`,
    });

    new cdk.CfnOutput(this, 'DbCredentialsArn', {
      value: this.credentials.secretArn,
      exportName: `${this.stackName}-DbCredentialsArn`,
    });
  }
}
