import * as cdk from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as rds from 'aws-cdk-lib/aws-rds';
import { Construct } from 'constructs';
import { resourceName } from '../config';
import { NetworkStack } from './network-stack';

interface DatabaseStackProps extends cdk.StackProps {
  network: NetworkStack;
}

/**
 * DatabaseStack — RDS PostgreSQL 16 in private subnets.
 *
 * - db.t3.micro for POC (free-tier eligible)
 * - Single-AZ (Multi-AZ adds cost; enable for production)
 * - Credentials auto-generated by RDS and stored in Secrets Manager
 * - Automated backups retained for 7 days
 *
 * P4-05
 */
export class DatabaseStack extends cdk.Stack {
  public readonly instance: rds.DatabaseInstance;
  public readonly credentials: rds.DatabaseSecret;

  constructor(scope: Construct, id: string, props: DatabaseStackProps) {
    super(scope, id, props);

    const { vpc, rdsSg } = props.network;

    // RDS auto-rotated credentials stored in Secrets Manager
    this.credentials = new rds.DatabaseSecret(this, 'DbCredentials', {
      secretName: 'afterlight/db-credentials',
      username: 'afterlight',
    });

    const subnetGroup = new rds.SubnetGroup(this, 'DbSubnetGroup', {
      description: 'Afterlight RDS subnet group — private subnets',
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      subnetGroupName: resourceName('db-subnet-group'),
    });

    this.instance = new rds.DatabaseInstance(this, 'DbInstance', {
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_16,
      }),
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.MICRO),
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      subnetGroup,
      securityGroups: [rdsSg],
      credentials: rds.Credentials.fromSecret(this.credentials),
      databaseName: 'afterlight',
      instanceIdentifier: resourceName('postgres'),
      multiAz: false, // Enable for production
      storageEncrypted: true,
      allocatedStorage: 20,
      maxAllocatedStorage: 100, // Auto-scaling storage up to 100 GB
      backupRetention: cdk.Duration.days(7),
      deletionProtection: true, // Prevent accidental deletion of production data
      removalPolicy: cdk.RemovalPolicy.SNAPSHOT, // Snapshot on stack deletion
      enablePerformanceInsights: false, // Enable in production
      cloudwatchLogsExports: ['postgresql'],
    });

    // ── Outputs ───────────────────────────────────────────────────────────

    new cdk.CfnOutput(this, 'DbEndpoint', {
      value: this.instance.instanceEndpoint.hostname,
      exportName: `${this.stackName}-DbEndpoint`,
    });

    new cdk.CfnOutput(this, 'DbCredentialsArn', {
      value: this.credentials.secretArn,
      exportName: `${this.stackName}-DbCredentialsArn`,
    });
  }
}
