import * as cdk from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';
import { resourceName } from '../config';
import { EnvironmentConfig } from '../environment-config';
import { NetworkStack } from './network-stack';

interface DatabaseStackProps extends cdk.StackProps {
  network: NetworkStack;
  config: EnvironmentConfig;
}

/**
 * DatabaseStack — RDS PostgreSQL 16 in private subnets.
 *
 * - db.t3.micro for POC (free-tier eligible)
 * - Single-AZ (Multi-AZ adds cost; enable for production)
 * - Credentials auto-generated by RDS and stored in Secrets Manager
 * - Automated backups retained for 7 days
 *
 * P4-05
 */
export class DatabaseStack extends cdk.Stack {
  public readonly instance: rds.DatabaseInstance;
  public readonly credentials: rds.DatabaseSecret;

  constructor(scope: Construct, id: string, props: DatabaseStackProps) {
    super(scope, id, props);

    const { config } = props;
    const { vpc, rdsSg } = props.network;

    // RDS auto-rotated credentials stored in Secrets Manager
    this.credentials = new rds.DatabaseSecret(this, 'DbCredentials', {
      secretName: 'tarpan/db-credentials',
      username: 'tarpan',
    });

    const subnetGroup = new rds.SubnetGroup(this, 'DbSubnetGroup', {
      description: 'Tarpan RDS subnet group - private subnets',
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      subnetGroupName: resourceName('db-subnet-group'),
    });

    this.instance = new rds.DatabaseInstance(this, 'DbInstance', {
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_16,
      }),
      instanceType: config.dbInstanceType,
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      subnetGroup,
      securityGroups: [rdsSg],
      credentials: rds.Credentials.fromSecret(this.credentials),
      databaseName: 'tarpan',
      instanceIdentifier: resourceName('postgres'),
      multiAz: config.dbMultiAz,
      storageEncrypted: true,
      allocatedStorage: 20,
      maxAllocatedStorage: 100,
      backupRetention: cdk.Duration.days(config.dbBackupRetentionDays),
      deletionProtection: config.dbDeletionProtection,
      removalPolicy: config.dbRemovalPolicy,
      enablePerformanceInsights: config.dbEnablePerformanceInsights,
      cloudwatchLogsExports: ['postgresql'],
    });

    // ── Credential rotation (P6-04) ─────────────────────────────────────────
    //
    // AWS-managed single-user rotation Lambda. Single-user rotation briefly
    // changes the live password, so the API picks up the new value only after
    // its next task restart — see infra/RESTORE_RUNBOOK.md.
    //
    // `instance.addRotationSingleUser()` would add the rotation Lambda's ingress
    // rule directly onto rdsSg (owned by NetworkStack) and reference the DB's
    // dynamic port — creating a NetworkStack→DatabaseStack reference on top of
    // the existing DatabaseStack→NetworkStack one, i.e. a cyclic stack
    // dependency. Building SecretRotation here, against rdsSg imported by id and
    // a constant Postgres port, keeps that ingress rule inside DatabaseStack and
    // breaks the cycle.

    if (config.secretRotationEnabled) {
      const rotationTarget: ec2.IConnectable = {
        connections: new ec2.Connections({
          securityGroups: [
            ec2.SecurityGroup.fromSecurityGroupId(this, 'RdsSgRef', rdsSg.securityGroupId),
          ],
          defaultPort: ec2.Port.tcp(5432),
        }),
      };

      new secretsmanager.SecretRotation(this, 'DbCredentialsRotation', {
        secret: this.instance.secret!,
        application: secretsmanager.SecretRotationApplication.POSTGRES_ROTATION_SINGLE_USER,
        vpc,
        vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
        target: rotationTarget,
        automaticallyAfter: cdk.Duration.days(config.secretRotationDays),
      });
    }

    // ── Outputs ───────────────────────────────────────────────────────────

    new cdk.CfnOutput(this, 'DbEndpoint', {
      value: this.instance.instanceEndpoint.hostname,
      exportName: `${this.stackName}-DbEndpoint`,
    });

    new cdk.CfnOutput(this, 'DbCredentialsArn', {
      value: this.credentials.secretArn,
      exportName: `${this.stackName}-DbCredentialsArn`,
    });
  }
}
